# Generated by Django 3.2 on 2023-09-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230913_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_level', models.SmallIntegerField(choices=[(0, '简单'), (1, '中等'), (2, '困难')], verbose_name='任务等级')),
                ('task_name', models.CharField(max_length=32, verbose_name='任务名称')),
                ('task_content', models.TextField(verbose_name='任务内容')),
                ('task_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin', verbose_name='任务负责人')),
            ],
        ),
    ]
